apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: prometheus-user-workload-trusted-ca-bundle
  namespace: openshift-user-workload-monitoring
